import { NextRequest } from 'next/server';
import {
  DEFAULT_CONTRIBUTION_PERIOD,
  getContributionDateRange,
} from '@/lib/contribution-period';
import {
  fetchContributions,
  getEdgeCache,
  mergeContributions,
  resolveTheme,
  runAfterResponse,
  stripSvgExtension,
  svgError,
  trackEmbedServed,
  SITE_URL,
  type EmbedPlatformEntry,
} from '@/lib/embed-render';
import { generateHeatmapSvg } from '@/lib/embed-svg';

// ─────────────────────────────────────────────────────────────────────────────
// OPERATIONAL CONSTRAINT (issue #96): this endpoint is consumed by GitHub's
// camo image proxy, which cannot execute JavaScript and therefore cannot pass
// Cloudflare bot challenges. Bot Fight Mode must stay OFF on the gitall.app
// zone — it applies zone-wide and CANNOT be skipped per-path with WAF custom
// rules on the free plan. Enabling it silently breaks every embedded heatmap
// in the wild. Abuse is mitigated instead by the edge cache below, a
// Cloudflare rate limiting rule scoped to /embed/*, and the "Block AI bots"
// managed rule (issue #97). If the zone is ever upgraded to Pro, use Super
// Bot Fight Mode with a skip rule on /embed/* and /api/* instead.
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// EDGE CACHING
//
// `Cache-Control: s-maxage` alone does NOT cause Cloudflare to cache a response
// generated by a Worker. It instructs downstream caches (camo, browsers) only.
// Measured against production before this change: a never-before-requested URL
// returned in the same ~115ms as a repeated one, and no `age` header was ever
// present — i.e. nothing was being served from Cloudflare's edge. The apparent
// speedup came from the per-isolate `contributionCache` in the /api/* routes,
// which is keyed by username and therefore survives URL changes.
//
// We therefore populate the Workers Cache API explicitly. The Cache-Control
// header is retained: camo and browsers still honour it, and it also governs
// how long the entry we `put` remains fresh.
// ─────────────────────────────────────────────────────────────────────────────

// 24-hour edge cache; stale responses are served for up to 1 hour while
// revalidating so that GitHub's camo proxy always gets a quick response.
//
// Safe to keep this long because nothing here is resolved server-side: the URL
// fully determines the response. The handle route (/embed/u/[handle]) caches a
// profile lookup and therefore uses a shorter TTL.
const CACHE_CONTROL = 'public, s-maxage=86400, stale-while-revalidate=3600';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> },
) {
  const { slug } = await params;

  // Accept both /embed/octocat and /embed/octocat.svg
  const primaryUsername = stripSvgExtension(slug);

  if (!primaryUsername) {
    return svgError('Missing username', 400, 'public, s-maxage=86400');
  }

  const searchParams = request.nextUrl.searchParams;

  // Normalize: treat empty/whitespace-only param values the same as absent.
  // Without this, `?github=` sets hasExplicitParams=true but produces no fetch,
  // returning "No platform usernames provided" even when a valid path slug exists.
  const explicitGithub = searchParams.get('github')?.trim() || null;
  const gitlabUsername = searchParams.get('gitlab')?.trim() || null;
  const bitbucketUsername = searchParams.get('bitbucket')?.trim() || null;
  const giteaUsername = searchParams.get('gitea')?.trim() || null;
  const giteaInstance = searchParams.get('instance')?.trim() || null;

  // When no explicit platform params are given, the path username is the
  // GitHub username (simple single-platform case: /embed/octocat.svg).
  // When any explicit params are present, rely only on those params —
  // the path is treated as a URL slug and does not imply a GitHub lookup.
  const hasExplicitParams =
    explicitGithub !== null ||
    gitlabUsername !== null ||
    bitbucketUsername !== null ||
    giteaUsername !== null;

  const githubUsername = hasExplicitParams
    ? (explicitGithub ?? null)
    : primaryUsername;

  const theme = resolveTheme(searchParams.get('theme'));

  const cache = getEdgeCache();
  const cacheKey = new Request(request.url, { method: 'GET' });

  // Serve from the edge when we already have this exact URL. `embed_served`
  // still fires on this path so the event tracks impressions that reach the
  // Worker rather than only cache fills; `cache_status` distinguishes them.
  if (cache) {
    const hit = await cache.match(cacheKey);
    if (hit) {
      trackEmbedServed(
        request,
        hit.headers.get('x-gitall-platforms'),
        theme,
        'hit',
        'slug',
      );
      return hit;
    }
  }

  const entries: EmbedPlatformEntry[] = [];
  if (githubUsername) {
    entries.push({ platform: 'github', username: githubUsername });
  }
  if (gitlabUsername) {
    entries.push({ platform: 'gitlab', username: gitlabUsername });
  }
  if (bitbucketUsername) {
    entries.push({ platform: 'bitbucket', username: bitbucketUsername });
  }
  if (giteaUsername) {
    entries.push({
      platform: 'gitea',
      username: giteaUsername,
      instanceUrl: giteaInstance,
    });
  }

  if (entries.length === 0) {
    return svgError(
      'No platform usernames provided',
      400,
      'public, s-maxage=86400',
    );
  }

  // Default to last 12 months
  const { from, to } = getContributionDateRange(DEFAULT_CONTRIBUTION_PERIOD);

  const { data: validResults, hasTransient } = await fetchContributions(
    request.nextUrl.origin,
    entries,
    from,
    to,
  );

  if (validResults.length === 0) {
    // Only cache the 404 when every failure was definitive (user not found).
    // If any platform timed out, returned 5xx, or was rate-limited the cause
    // is transient and we must not cache — doing so would serve broken embeds
    // to real users during an upstream blip.
    const errorCacheDirective = hasTransient
      ? 'no-store'
      : 'public, s-maxage=3600';
    const errorResponse = svgError(
      'No contribution data found',
      404,
      errorCacheDirective,
    );
    if (cache && !hasTransient) {
      runAfterResponse(cache.put(cacheKey, errorResponse.clone()));
    }
    return errorResponse;
  }

  const merged = mergeContributions(validResults);
  const svg = generateHeatmapSvg(merged, { theme, siteUrl: SITE_URL });
  const platforms = validResults.map((r) => r.platform).join('+');

  const response = new Response(svg, {
    headers: {
      'Content-Type': 'image/svg+xml; charset=utf-8',
      'Cache-Control': CACHE_CONTROL,
      'X-Robots-Tag': 'noindex',
      // Cloudflare's edge cache only understands `Vary: Accept-Encoding`.
      // Set it explicitly so the RSC negotiation headers OpenNext applies
      // globally do not suppress caching of this image response.
      Vary: 'Accept-Encoding',
      // Read back on a cache hit so the analytics event can report platforms
      // without re-running the upstream fetches.
      'x-gitall-platforms': platforms,
    },
  });

  if (cache) {
    runAfterResponse(cache.put(cacheKey, response.clone()));
  }

  trackEmbedServed(request, platforms, theme, 'miss', 'slug');

  return response;
}
